<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>JobAutofill.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
    <ProjectReference Include="../JobAutofill.Core/JobAutofill.Core.csproj" />
    <ProjectReference Include="../JobAutofill.Domain/JobAutofill.Domain.csproj" />
  </ItemGroup>
</Project>
